<?php

namespace App;

use App\Scopes\ReverseScope;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new ReverseScope());
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function friends(){
        return $this->belongsToMany(User::class, 'friends','friend_id','user_id');
    }
}
